const LOWEST_NODE_VERSION = '12.0.0'
const DEFAULT_CLI_HOME = '.hyhan-cli'
const DEFAULT_CONFIG_FILENAME = '.hyhanrc'

module.exports = {
  LOWEST_NODE_VERSION,
  DEFAULT_CLI_HOME,
  DEFAULT_CONFIG_FILENAME,
}
